// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzUyVLLIWkAwI7kmy5vPvroh5rvFaDzIo',
    appId: '1:607221026677:web:d3dd232188f5d6207ecd3c',
    messagingSenderId: '607221026677',
    projectId: 'shopping-app-303aa',
    authDomain: 'shopping-app-303aa.firebaseapp.com',
    databaseURL: 'https://shopping-app-303aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopping-app-303aa.appspot.com',
    measurementId: 'G-67V42GR2DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNAsJ2td7aw8FUb_eLjaSJfZgfeDsLiZY',
    appId: '1:607221026677:android:b3d2de07e358f9447ecd3c',
    messagingSenderId: '607221026677',
    projectId: 'shopping-app-303aa',
    databaseURL: 'https://shopping-app-303aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopping-app-303aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEy58_RyyPtFFe-HebCsYyDYC2-WFZsX4',
    appId: '1:607221026677:ios:6526c4fbbc6e602b7ecd3c',
    messagingSenderId: '607221026677',
    projectId: 'shopping-app-303aa',
    databaseURL: 'https://shopping-app-303aa-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shopping-app-303aa.appspot.com',
    iosBundleId: 'dev.erkinov.shoppingApp',
  );
}
